begin;

alter table public.borrow_transactions
    add column if not exists status_details jsonb not null default '{}'::jsonb,
    add column if not exists status_remarks text,
    add column if not exists status_updated_at timestamptz;

create table if not exists public.asset_status_history (
    id bigint generated by default as identity primary key,
    item_type text not null check (item_type in ('Medical Equipment', 'Mobility Asset')),
    inventory_item_id text not null,
    transaction_id text,
    previous_status text,
    new_status text not null check (new_status in (
        'Available', 'Borrowed', 'Returned', 'Missing', 'Damaged', 'For Repair'
    )),
    quantity integer not null default 1 check (quantity > 0),
    remarks text,
    details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
    changed_by uuid,
    changed_at timestamptz not null default now()
);

create index if not exists asset_status_history_item_idx
on public.asset_status_history (item_type, inventory_item_id, changed_at desc);

create index if not exists asset_status_history_transaction_idx
on public.asset_status_history (transaction_id, changed_at desc);

alter table public.asset_status_history enable row level security;
revoke all on table public.asset_status_history from anon, authenticated;
grant select on table public.asset_status_history to authenticated;
grant usage, select on sequence public.asset_status_history_id_seq to authenticated;

drop policy if exists "Active users can read asset status history"
on public.asset_status_history;
create policy "Active users can read asset status history"
on public.asset_status_history for select to authenticated
using (public.medtrack_is_active_user());

create or replace function public.medtrack_apply_new_borrow_status()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if new.item_type = 'Medical Equipment' then
        update public.medical_equipment
        set status = 'Borrowed', updated_at = now()
        where id = new.inventory_item_id;
    elsif new.item_type = 'Mobility Asset' then
        update public.mobility_assets
        set status = 'Borrowed', updated_at = now()
        where id = new.inventory_item_id;
    else
        return new;
    end if;

    insert into public.asset_status_history (
        item_type, inventory_item_id, transaction_id,
        previous_status, new_status, quantity, remarks,
        details, changed_by, changed_at
    ) values (
        new.item_type, new.inventory_item_id, new.id,
        'Available', 'Borrowed', greatest(new.quantity, 1), new.remarks,
        jsonb_build_object(
            'borrower', new.borrower,
            'department', new.department,
            'borrowedAt', new.borrowed_at,
            'dueDate', new.due_date,
            'purpose', new.purpose,
            'destination', new.destination
        ),
        auth.uid(), coalesce(new.borrowed_at, now())
    );

    insert into public.audit_events (
        actor_id, action, module, entity_type, entity_id, details, metadata
    ) values (
        auth.uid(), 'Created', 'Status', 'borrow_transaction', new.id,
        new.item_name || ' was set to Borrowed for ' || new.borrower || '.',
        jsonb_build_object(
            'itemType', new.item_type,
            'inventoryItemId', new.inventory_item_id,
            'status', 'Borrowed',
            'quantity', new.quantity
        )
    );
    return new;
end;
$$;

drop trigger if exists apply_new_borrow_status on public.borrow_transactions;
create trigger apply_new_borrow_status
after insert on public.borrow_transactions
for each row
when (new.item_type in ('Medical Equipment', 'Mobility Asset'))
execute function public.medtrack_apply_new_borrow_status();

create or replace function public.medtrack_update_borrow_status(
    p_transaction_id text,
    p_status text,
    p_details jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_transaction public.borrow_transactions%rowtype;
    v_inventory_item_id text;
    v_requested_status text := coalesce(trim(p_status), '');
    v_transaction_status text;
    v_was_returned boolean;
    v_effective_at timestamptz;
    v_quantity integer;
    v_reported_by text;
    v_condition text;
    v_location text;
    v_remarks text;
begin
    if not exists (
        select 1 from public.profiles
        where id = auth.uid() and status = 'active' and role in ('admin', 'staff')
    ) then
        raise exception 'An active MedTrack account is required.' using errcode = '42501';
    end if;

    if v_requested_status not in (
        'Available', 'Returned', 'Missing', 'Damaged', 'For Repair'
    ) then
        raise exception 'Select a valid item status.';
    end if;

    if p_details is null or jsonb_typeof(p_details) <> 'object' then
        raise exception 'Status details are required.';
    end if;

    begin
        v_effective_at := nullif(trim(p_details ->> 'effectiveAt'), '')::timestamptz;
        v_quantity := nullif(trim(p_details ->> 'quantity'), '')::integer;
    exception when others then
        raise exception 'Enter a valid status date and quantity.';
    end;
    v_reported_by := nullif(trim(p_details ->> 'reportedBy'), '');
    v_condition := nullif(trim(p_details ->> 'condition'), '');
    v_location := nullif(trim(p_details ->> 'location'), '');
    v_remarks := nullif(trim(p_details ->> 'remarks'), '');

    if v_effective_at is null or v_quantity is null or v_quantity < 1 or
       v_reported_by is null or v_condition is null or
       v_location is null or v_remarks is null then
        raise exception 'Complete all required status information.';
    end if;

    select * into v_transaction
    from public.borrow_transactions
    where id = p_transaction_id
    for update;

    if not found then
        raise exception 'The borrowing record was not found.';
    end if;
    if v_transaction.item_type not in ('Medical Equipment', 'Mobility Asset') then
        raise exception 'Medical supplies are not supported by the Status module.';
    end if;
    if v_quantity <> v_transaction.quantity then
        raise exception 'The status quantity must match the borrowed quantity.';
    end if;

    v_inventory_item_id := v_transaction.inventory_item_id;
    if v_inventory_item_id is null then
        if v_transaction.item_type = 'Medical Equipment' then
            select id into v_inventory_item_id from public.medical_equipment
            where lower(trim(name)) = lower(trim(v_transaction.item_name))
            order by id limit 1;
        else
            select id into v_inventory_item_id from public.mobility_assets
            where lower(trim(name)) = lower(trim(v_transaction.item_name))
            order by id limit 1;
        end if;
    end if;
    if v_inventory_item_id is null then
        raise exception 'The related inventory item was not found.';
    end if;

    v_was_returned := v_transaction.status = 'Returned' or
        coalesce(v_transaction.inventory_returned, false);
    v_transaction_status := case
        when v_requested_status in ('Available', 'Returned') then 'Returned'
        else v_requested_status
    end;

    if v_transaction_status = 'Returned' then
        if coalesce(v_transaction.inventory_adjusted, false) and not v_was_returned then
            if v_transaction.item_type = 'Medical Equipment' then
                update public.medical_equipment
                set quantity = quantity + v_transaction.quantity,
                    status = 'Available', condition = v_condition,
                    location = v_location, updated_at = now()
                where id = v_inventory_item_id;
            else
                update public.mobility_assets
                set status = 'Available', condition = v_condition,
                    location = v_location, updated_at = now()
                where id = v_inventory_item_id;
            end if;
        else
            if v_transaction.item_type = 'Medical Equipment' then
                update public.medical_equipment
                set status = 'Available', condition = v_condition,
                    location = v_location, updated_at = now()
                where id = v_inventory_item_id;
            else
                update public.mobility_assets
                set status = 'Available', condition = v_condition,
                    location = v_location, updated_at = now()
                where id = v_inventory_item_id;
            end if;
        end if;
    else
        if coalesce(v_transaction.inventory_adjusted, false) and v_was_returned then
            if v_transaction.item_type = 'Medical Equipment' then
                update public.medical_equipment
                set quantity = quantity - v_transaction.quantity, updated_at = now()
                where id = v_inventory_item_id and quantity >= v_transaction.quantity;
            else
                update public.mobility_assets set updated_at = now()
                where id = v_inventory_item_id and lower(status) = 'available';
            end if;
            if not found then
                raise exception 'The item is no longer available in the required quantity.';
            end if;
        end if;

        if v_transaction.item_type = 'Medical Equipment' then
            update public.medical_equipment
            set status = v_requested_status,
                condition = case
                    when v_requested_status = 'Damaged' then 'Damaged'
                    when v_requested_status = 'Missing' then 'Missing'
                    when v_requested_status = 'For Repair' then 'Needs Repair'
                    else condition
                end,
                location = v_location, updated_at = now()
            where id = v_inventory_item_id;
        else
            update public.mobility_assets
            set status = v_requested_status,
                condition = case
                    when v_requested_status = 'Damaged' then 'Damaged'
                    when v_requested_status = 'Missing' then 'Missing'
                    when v_requested_status = 'For Repair' then 'Needs Repair'
                    else condition
                end,
                location = v_location, updated_at = now()
            where id = v_inventory_item_id;
        end if;
    end if;

    update public.borrow_transactions
    set inventory_item_id = v_inventory_item_id,
        status = v_transaction_status,
        return_date = case when v_transaction_status = 'Returned'
            then (v_effective_at at time zone 'Asia/Manila')::date else null end,
        inventory_returned = case when coalesce(inventory_adjusted, false)
            then v_transaction_status = 'Returned' else inventory_returned end,
        status_details = p_details,
        status_remarks = v_remarks,
        status_updated_at = v_effective_at,
        updated_at = now()
    where id = p_transaction_id;

    insert into public.asset_status_history (
        item_type, inventory_item_id, transaction_id, previous_status,
        new_status, quantity, remarks, details, changed_by, changed_at
    ) values (
        v_transaction.item_type, v_inventory_item_id, p_transaction_id,
        v_transaction.status, v_requested_status, v_quantity, v_remarks,
        p_details, auth.uid(), v_effective_at
    );

    insert into public.audit_events (
        actor_id, action, module, entity_type, entity_id, details, metadata
    ) values (
        auth.uid(), 'Updated', 'Status', 'borrow_transaction', p_transaction_id,
        v_transaction.item_name || ' changed from ' || v_transaction.status ||
            ' to ' || v_requested_status || '. ' || v_remarks,
        jsonb_build_object(
            'itemType', v_transaction.item_type,
            'inventoryItemId', v_inventory_item_id,
            'previousStatus', v_transaction.status,
            'newStatus', v_requested_status,
            'reportedBy', v_reported_by,
            'location', v_location,
            'condition', v_condition,
            'quantity', v_quantity
        )
    );

    return jsonb_build_object(
        'id', p_transaction_id,
        'status', v_requested_status,
        'transactionStatus', v_transaction_status,
        'available', v_transaction_status = 'Returned'
    );
end;
$$;

revoke all on function public.medtrack_update_borrow_status(text, text, jsonb)
from public;
grant execute on function public.medtrack_update_borrow_status(text, text, jsonb)
to authenticated;

create or replace function public.medtrack_update_borrow_status(
    p_transaction_id text,
    p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_transaction public.borrow_transactions%rowtype;
begin
    select * into v_transaction from public.borrow_transactions
    where id = p_transaction_id;
    if not found then raise exception 'The borrowing record was not found.'; end if;
    return public.medtrack_update_borrow_status(
        p_transaction_id,
        p_status,
        jsonb_build_object(
            'effectiveAt', now(),
            'quantity', v_transaction.quantity,
            'reportedBy', 'MedTrack User',
            'condition', case when p_status = 'Damaged' then 'Damaged' else 'Good' end,
            'location', coalesce(v_transaction.destination, 'Not specified'),
            'remarks', 'Status updated through the legacy workflow.'
        )
    );
end;
$$;

revoke all on function public.medtrack_update_borrow_status(text, text) from public;
grant execute on function public.medtrack_update_borrow_status(text, text) to authenticated;

do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1 from pg_publication_tables
           where pubname = 'supabase_realtime' and schemaname = 'public'
             and tablename = 'borrow_transactions'
       ) then
        alter publication supabase_realtime add table public.borrow_transactions;
    end if;
end
$$;

notify pgrst, 'reload schema';
commit;
