-- Synchronize per-user notification preferences and record sanitized client
-- failures without exposing one user's information to another user.

create table if not exists public.notification_preferences (
    user_id uuid primary key references auth.users(id) on delete cascade,
    state jsonb not null default '{"readIds":[],"dismissed":[]}'::jsonb,
    updated_at timestamptz not null default now(),
    constraint notification_preferences_state_object
        check (jsonb_typeof(state) = 'object'),
    constraint notification_preferences_state_size
        check (octet_length(state::text) <= 131072)
);

alter table public.notification_preferences enable row level security;
revoke all on table public.notification_preferences from anon, authenticated;
grant select, insert, update on table public.notification_preferences to authenticated;

drop policy if exists "Users manage their notification preferences"
on public.notification_preferences;
create policy "Users manage their notification preferences"
on public.notification_preferences for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.client_error_events (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    page text not null,
    error_name text not null default 'Error',
    message text not null,
    context jsonb not null default '{}'::jsonb,
    occurred_at timestamptz not null default now(),
    constraint client_error_page_length check (char_length(page) between 1 and 240),
    constraint client_error_name_length check (char_length(error_name) between 1 and 100),
    constraint client_error_message_length check (char_length(message) between 1 and 1000),
    constraint client_error_context_object check (jsonb_typeof(context) = 'object'),
    constraint client_error_context_size check (octet_length(context::text) <= 8192)
);

create index if not exists client_error_events_occurred_at_idx
    on public.client_error_events (occurred_at desc);
create index if not exists client_error_events_user_id_idx
    on public.client_error_events (user_id, occurred_at desc);

alter table public.client_error_events enable row level security;
revoke all on table public.client_error_events from anon, authenticated;
grant insert, select on table public.client_error_events to authenticated;
grant usage, select on sequence public.client_error_events_id_seq to authenticated;

drop policy if exists "Users report their own client errors"
on public.client_error_events;
create policy "Users report their own client errors"
on public.client_error_events for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Verified admins read client errors"
on public.client_error_events;
create policy "Verified admins read client errors"
on public.client_error_events for select to authenticated
using (
    public.medtrack_is_admin()
    and public.medtrack_admin_mfa_satisfied()
);

create or replace function public.medtrack_audit_client_error()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    insert into public.audit_events (
        actor_id, action, module, entity_type, entity_id, details, metadata
    ) values (
        new.user_id,
        'Client Error',
        'System',
        'client_error',
        new.id::text,
        new.error_name || ' on ' || new.page || ': ' || new.message,
        jsonb_build_object('page', new.page, 'errorName', new.error_name)
    );
    return new;
end;
$$;

drop trigger if exists audit_client_error on public.client_error_events;
create trigger audit_client_error
after insert on public.client_error_events
for each row execute function public.medtrack_audit_client_error();

create or replace function public.medtrack_purge_client_errors(
    p_older_than_days integer default 90
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    deleted_count integer;
begin
    if not public.medtrack_is_admin()
       or not public.medtrack_admin_mfa_satisfied() then
        raise exception 'Verified administrator access is required.'
            using errcode = '42501';
    end if;

    if p_older_than_days < 30 or p_older_than_days > 3650 then
        raise exception 'Retention must be between 30 and 3650 days.';
    end if;

    delete from public.client_error_events
    where occurred_at < now() - make_interval(days => p_older_than_days);
    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;

revoke all on function public.medtrack_purge_client_errors(integer) from public;
grant execute on function public.medtrack_purge_client_errors(integer) to authenticated;

notify pgrst, 'reload schema';
