
create table if not exists public.audit_events (
    id bigint generated by default as identity primary key,
    occurred_at timestamptz not null default now(),
    actor_id uuid,
    actor_name text not null default 'System',
    actor_role text not null default 'system',
    action text not null,
    module text not null,
    entity_type text,
    entity_id text,
    details text not null,
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists audit_events_occurred_at_idx
    on public.audit_events (occurred_at desc);

create index if not exists audit_events_actor_id_idx
    on public.audit_events (actor_id, occurred_at desc);

create index if not exists audit_events_module_action_idx
    on public.audit_events (module, action, occurred_at desc);

alter table public.audit_events enable row level security;

revoke all on table public.audit_events from anon, authenticated;
grant select on table public.audit_events to authenticated;
grant select, insert on table public.audit_events to service_role;
grant usage, select on sequence public.audit_events_id_seq to service_role;

drop policy if exists "Admins can read audit events"
on public.audit_events;

create policy "Admins can read audit events"
on public.audit_events for select to authenticated
using (public.medtrack_is_admin());

create or replace function public.medtrack_enrich_audit_actor()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_profile public.profiles%rowtype;
begin
    if new.actor_id is null then
        new.actor_id := auth.uid();
    end if;

    if new.actor_id is not null then
        select * into v_profile
        from public.profiles
        where id = new.actor_id;

        if found then
            new.actor_name := coalesce(
                nullif(trim(v_profile.full_name), ''),
                nullif(trim(v_profile.username), ''),
                'Unknown User'
            );
            new.actor_role := coalesce(nullif(trim(v_profile.role), ''), 'unknown');
        end if;
    end if;

    new.occurred_at := coalesce(new.occurred_at, now());
    new.metadata := coalesce(new.metadata, '{}'::jsonb);
    return new;
end;
$$;

drop trigger if exists enrich_audit_actor on public.audit_events;

create trigger enrich_audit_actor
before insert on public.audit_events
for each row
execute function public.medtrack_enrich_audit_actor();

create or replace function public.medtrack_record_auth_event(p_action text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_action text := initcap(lower(trim(coalesce(p_action, ''))));
begin
    if not public.medtrack_is_active_user() then
        raise exception 'An active MedTrack account is required.'
            using errcode = '42501';
    end if;

    if v_action not in ('Login', 'Logout') then
        raise exception 'Unsupported authentication audit action.';
    end if;

    insert into public.audit_events (
        actor_id,
        action,
        module,
        entity_type,
        entity_id,
        details,
        metadata
    ) values (
        auth.uid(),
        v_action,
        'Authentication',
        'session',
        auth.uid()::text,
        case v_action
            when 'Login' then 'User signed in to MedTrack.'
            else 'User signed out of MedTrack.'
        end,
        jsonb_build_object('source', 'authenticated_client')
    );
end;
$$;

revoke all on function public.medtrack_record_auth_event(text) from public;
grant execute on function public.medtrack_record_auth_event(text) to authenticated;

create or replace function public.medtrack_audit_table_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_row jsonb;
    v_old_row jsonb;
    v_entity_id text;
    v_action text;
    v_module text;
    v_changed_fields jsonb := '[]'::jsonb;
begin
    v_row := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
    v_old_row := case when tg_op = 'UPDATE' then to_jsonb(old) else null end;
    v_entity_id := coalesce(v_row ->> 'id', 'unknown');
    v_action := case tg_op
        when 'INSERT' then 'Created'
        when 'UPDATE' then 'Updated'
        when 'DELETE' then 'Deleted'
    end;

    v_module := case tg_table_name
        when 'medical_supplies' then 'Medical Supplies'
        when 'medical_equipment' then 'Medical Equipment'
        when 'mobility_assets' then 'Mobility'
        when 'borrow_transactions' then 'Borrow and Return'
        when 'emergency_requests' then 'Emergency Response'
        else 'System'
    end;

    if tg_op = 'UPDATE' then
        select coalesce(jsonb_agg(changed.key order by changed.key), '[]'::jsonb)
        into v_changed_fields
        from jsonb_each(v_row) as changed(key, value)
        where changed.key <> 'updated_at'
          and changed.value is distinct from v_old_row -> changed.key;

        if jsonb_array_length(v_changed_fields) = 0 then
            return new;
        end if;
    end if;

    insert into public.audit_events (
        actor_id,
        action,
        module,
        entity_type,
        entity_id,
        details,
        metadata
    ) values (
        auth.uid(),
        v_action,
        v_module,
        tg_table_name,
        v_entity_id,
        v_action || ' ' || lower(v_module) || ' record ' || v_entity_id || '.',
        jsonb_build_object(
            'databaseOperation', tg_op,
            'changedFields', v_changed_fields
        )
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

do $$
declare
    v_table text;
begin
    foreach v_table in array array[
        'medical_supplies',
        'medical_equipment',
        'mobility_assets',
        'borrow_transactions',
        'emergency_requests'
    ]
    loop
        execute format('drop trigger if exists audit_table_change on public.%I', v_table);
        execute format(
            'create trigger audit_table_change after insert or update or delete on public.%I for each row execute function public.medtrack_audit_table_change()',
            v_table
        );
    end loop;
end
$$;

create or replace function public.medtrack_prevent_audit_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    raise exception 'Audit events are immutable.' using errcode = '42501';
end;
$$;

drop trigger if exists prevent_audit_mutation on public.audit_events;

create trigger prevent_audit_mutation
before update or delete on public.audit_events
for each row
execute function public.medtrack_prevent_audit_mutation();

notify pgrst, 'reload schema';
